#include "cbase.h"
#include "eventlist.h"

void RegisterZMAnimEvents()
{
    // It seems you can't use AE_TYPE_SHARED
	REGISTER_SHARED_ANIMEVENT( AE_ZM_MELEEHIT, AE_TYPE_CLIENT | AE_TYPE_SERVER );
	REGISTER_SHARED_ANIMEVENT( AE_ZM_REVOLVERSHOOT, AE_TYPE_CLIENT | AE_TYPE_SERVER );
	REGISTER_SHARED_ANIMEVENT( AE_ZM_BEAMON, AE_TYPE_SERVER );
	REGISTER_SHARED_ANIMEVENT( AE_ZM_BEAMOFF, AE_TYPE_SERVER );
	REGISTER_SHARED_ANIMEVENT( AE_ZM_LIGHTERFLAME, AE_TYPE_SERVER );
	REGISTER_SHARED_ANIMEVENT( AE_ZM_CLOTHFLAME, AE_TYPE_SERVER );
}