#include "cbase.h"
#include "eventlist.h"
#include "activitylist.h"

// memdbgon must be the last include file in a .cpp file!!!
#include "tier0/memdbgon.h"

void RegisterZMAnimEvents()
{
    // It seems you can't use AE_TYPE_SHARED
	REGISTER_SHARED_ANIMEVENT( AE_ZM_MELEEHIT, AE_TYPE_CLIENT | AE_TYPE_SERVER );
	REGISTER_SHARED_ANIMEVENT( AE_ZM_REVOLVERSHOOT, AE_TYPE_CLIENT | AE_TYPE_SERVER );
	REGISTER_SHARED_ANIMEVENT( AE_ZM_BEAMON, AE_TYPE_SERVER );
	REGISTER_SHARED_ANIMEVENT( AE_ZM_BEAMOFF, AE_TYPE_SERVER );
	REGISTER_SHARED_ANIMEVENT( AE_ZM_LIGHTERFLAME, AE_TYPE_SERVER );
	REGISTER_SHARED_ANIMEVENT( AE_ZM_CLOTHFLAME, AE_TYPE_CLIENT | AE_TYPE_SERVER );

    // Zombies
    // Even though most of these are used on the client only, we'll have to register them for both to get them to work on client. For whatever reason.
	REGISTER_SHARED_ANIMEVENT( AE_ZOMBIE_STEP_LEFT, AE_TYPE_CLIENT | AE_TYPE_SERVER );
	REGISTER_SHARED_ANIMEVENT( AE_ZOMBIE_STEP_RIGHT, AE_TYPE_CLIENT | AE_TYPE_SERVER );
	REGISTER_SHARED_ANIMEVENT( AE_ZOMBIE_SCUFF_LEFT, AE_TYPE_CLIENT | AE_TYPE_SERVER );
	REGISTER_SHARED_ANIMEVENT( AE_ZOMBIE_SCUFF_RIGHT, AE_TYPE_CLIENT | AE_TYPE_SERVER );

    REGISTER_SHARED_ANIMEVENT( AE_ZOMBIE_ATTACK_SCREAM, AE_TYPE_CLIENT | AE_TYPE_SERVER );
    REGISTER_SHARED_ANIMEVENT( AE_ZOMBIE_STARTSWAT, AE_TYPE_CLIENT | AE_TYPE_SERVER );

	REGISTER_SHARED_ANIMEVENT( AE_FASTZOMBIE_GALLOP_LEFT, AE_TYPE_CLIENT | AE_TYPE_SERVER );
	REGISTER_SHARED_ANIMEVENT( AE_FASTZOMBIE_GALLOP_RIGHT, AE_TYPE_CLIENT | AE_TYPE_SERVER );
	REGISTER_SHARED_ANIMEVENT( AE_FASTZOMBIE_LEAP, AE_TYPE_CLIENT | AE_TYPE_SERVER );
}

void RegisterZMActivities()
{
    // NOTE: Has to be in the same order as ai_activity.h
    REGISTER_SHARED_ACTIVITY( ACT_ZM_IDLE_SLEDGE );
    REGISTER_SHARED_ACTIVITY( ACT_ZM_RUN_SLEDGE );
    REGISTER_SHARED_ACTIVITY( ACT_ZM_IDLE_CROUCH_SLEDGE );
    REGISTER_SHARED_ACTIVITY( ACT_ZM_WALK_CROUCH_SLEDGE );
    REGISTER_SHARED_ACTIVITY( ACT_ZM_GESTURE_RANGE_ATTACK_SLEDGE );
    REGISTER_SHARED_ACTIVITY( ACT_ZM_JUMP_SLEDGE );

    REGISTER_SHARED_ACTIVITY( ACT_ZOM_SWATLEFTMID );
    REGISTER_SHARED_ACTIVITY( ACT_ZOM_SWATLEFTLOW );
    REGISTER_SHARED_ACTIVITY( ACT_ZOM_SWATRIGHTMID );
    REGISTER_SHARED_ACTIVITY( ACT_ZOM_SWATRIGHTLOW );

    REGISTER_SHARED_ACTIVITY( ACT_FASTZOMBIE_FRENZY );
    REGISTER_SHARED_ACTIVITY( ACT_FASTZOMBIE_BIG_SLASH );
    REGISTER_SHARED_ACTIVITY( ACT_FASTZOMBIE_LAND_RIGHT );
    REGISTER_SHARED_ACTIVITY( ACT_FASTZOMBIE_LAND_LEFT );
    REGISTER_SHARED_ACTIVITY( ACT_FASTZOMBIE_LEAP_STRIKE );
}
