#pragma once


#include "zmr_zombiebase.h"


enum
{
	SCHED_FASTZOMBIE_RANGE_ATTACK1 = LAST_BASE_ZOMBIE_SCHEDULE,
	SCHED_FASTZOMBIE_UNSTICK_JUMP,
	SCHED_FASTZOMBIE_CLIMBING_UNSTICK_JUMP,
	SCHED_FASTZOMBIE_MELEE_ATTACK1,

    // ZM
	SCHED_FASTZOMBIE_CEILING_JUMP,
	SCHED_FASTZOMBIE_CEILING_CLING,
};

enum 
{
    TASK_FASTZOMBIE_DO_ATTACK = LAST_BASE_ZOMBIE_TASK,
    TASK_FASTZOMBIE_LAND_RECOVER,
    TASK_FASTZOMBIE_UNSTICK_JUMP,
    TASK_FASTZOMBIE_JUMP_BACK,
    TASK_FASTZOMBIE_VERIFY_ATTACK,

    // ZM
    TASK_FASTZOMBIE_JUMP_TO_CEILING,
    TASK_FASTZOMBIE_CLING_TO_CEILING,
    TASK_FASTZOMBIE_CHECK_CEILING,
};

enum
{
    COND_FASTZOMBIE_CLIMB_TOUCH	= LAST_BASE_ZOMBIE_CONDITION,
};
